#cloud-config

coreos:
  units:
  - name: etcd2.service
    command: start
    enable: true
    drop-ins:
    - name: 15-deps.conf
      content: |
        [Unit]
        Description=Etcd2 - unit for etcd
        Wants=kmsctl-certs.service
        [Service]
        PermissionsStartOnly=true
        RuntimeDirectory=etcd2
        RuntimeDirectoryMode=0700
        ExecStartPre=/usr/bin/mkdir -p /var/lib/etcd2
        ExecStartPre=/usr/bin/chown -R etcd:etcd /etc/ssl/kubernetes /var/lib/etcd2
        ExecStartPre=/usr/bin/chmod 0744 /var/lib/etcd2
        ExecStartPre=/usr/bin/systemctl --quiet is-active kmsctl-certs.service
        EnvironmentFile=/etc/etcd-environment
        Restart=on-failure
        RestartSec=10
  - name: kmsctl-certs.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=KMSCtl - download certs
      [Service]
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/mkdir -p /etc/ssl/kubernetes
      ExecStartPre=/usr/bin/chmod 0744 /etc/ssl/kubernetes /var/lib/etcd2
      ExecStartPre=/usr/bin/wget https://github.com/gambol99/kmsctl/releases/download/v1.0.4/kmsctl-linux-amd64 -O /opt/bin/kmsctl
      ExecStartPre=/usr/bin/chmod +x /opt/bin/kmsctl
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdcertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdkeyobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${cacertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdproxycertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdproxykeyobject}
      ExecStartPre=/usr/bin/echo "Completed Cert downloads"
      ExecStartPre=/usr/bin/bash -c "cp -f /etc/ssl/kubernetes/* /etc/ssl/certs"
      ExecStartPre=/usr/bin/bash -c "chmod 0644 /etc/ssl/kubernetes/*"
      ExecStartPre=/usr/bin/chown -R etcd:etcd /etc/ssl/kubernetes /var/lib/etcd2
      ExecStartPre=/usr/sbin/update-ca-certificates
      ExecStart=/bin/ls /etc/ssl/kubernetes/${etcdcertobject} /etc/ssl/kubernetes/${etcdkeyobject} /etc/ssl/kubernetes/${cacertobject} /etc/ssl/kubernetes/${etcdproxycertobject} /etc/ssl/kubernetes/${etcdproxykeyobject}
      Restart=on-failure
      RestartSec=10
      TimeoutStartSec=300
write_files:
- path: /etc/profile.env
  content: |
    export ETCDCTL_ENDPOINT=https://127.0.0.1:2379
    export ETCDCTL_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    export ETCDCTL_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    export ETCDCTL_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
    source /etc/etcd-environment
- path: /etc/etcd-environment
  permissions: 0644
  content: |
    ETCD_TRUSTED_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    ETCD_CERT_FILE=/etc/ssl/kubernetes/${etcdproxycertobject}
    ETCD_KEY_FILE=/etc/ssl/kubernetes/${etcdproxykeyobject}
    ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    ETCD_PEER_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    ETCD_PEER_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
    ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
    ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
    ETCD_CLIENT_CERT_AUTH=true
    ETCD_PEER_CLIENT_CERT_AUTH=true
    ETCD_INITIAL_CLUSTER=${etcd_memberlist}
    ETCD_PROXY=on
