apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --insecure-bind-address=0.0.0.0
    - --etcd-servers=https://127.0.0.1:2379
    - --allow-privileged=true
    - --service-cluster-ip-range=10.3.0.0/24
    - --secure-port=443
    - --advertise-address=0.0.0.0
    - --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota
    - --tls-cert-file=/etc/ssl/kubernetes/master.pem
    - --tls-ca-file=/etc/ssl/kubernetes/ca.pem
    - --tls-private-key-file=/etc/ssl/kubernetes/masterkey.pem
    - --client-ca-file=/etc/ssl/kubernetes/ca.pem
    - --service-account-key-file=/etc/ssl/kubernetes/masterkey.pem
    - --etcd-cafile=/etc/ssl/kubernetes/ca.pem
    - --etcd-certfile=/etc/ssl/kubernetes/etcd.pem
    - --etcd-keyfile=/etc/ssl/kubernetes/etcdkey.pem
    - --kubelet-certificate-authority=/etc/ssl/kubernetes/ca.pem
    - --kubelet-client-certificate=/etc/ssl/kubernetes/master.pem
    - --kubelet-client-key=/etc/ssl/kubernetes/masterkey.pem
    - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --anonymous-auth=false
    - --cloud-provider=aws
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/ssl/kubernetes
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/ssl/kubernetes
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
