apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.0
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    - --proxy-mode=iptables
    - --logtostderr=true
    securityContext:
      privileged: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10249
      initialDelaySeconds: 15
      timeoutSeconds: 15
    resources:
      requests:
        memory: 50Mi
      limits:
        memory: 8000Mi
    volumeMounts:
    - name: certs
      mountPath: /etc/ssl/certs
      readOnly: true
    - name: dbus
      mountPath: /var/run/dbus
      readOnly: false
  volumes:
  - name: certs
    hostPath:
      path: /etc/ssl/kubernetes
  - name: dbus
    hostPath:
      path: /var/run/dbus
