---
apiVersion: v1
kind: Service
metadata:
  name: polyshop-prod
  labels:
    app: polymerjs-shop-prod
    environment: production
    k8s-app: traefik-ingress-lb
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Shop"
    dns: route53
  annotations:
    domainName: "shop.capgemini-demo.com"
  namespace: polyshop
spec:
  type: LoadBalancer
  ports:
  - name: shopendpoint
    port: 80
    targetPort: 8080
  selector:
    app: polymerjs-shop
    environment: blue
