#cloud-config

coreos:
  flannel:
    interface: $private_ipv4
    etcd_endpoints: "https://127.0.0.1:2379"
    etcd_certfile: /etc/ssl/kubernetes/${etcdproxycertobject}
    etcd_keyfile: /etc/ssl/kubernetes/${etcdproxykeyobject}
    etcd_cafile: /etc/ssl/kubernetes/${cacertobject}
  units:
  - name: fleet.service
    command: stop
    enable: false
  - name: systemd-sysctl.service
    command: restart
  - name: etcd2.service
    command: start
    enable: true
    drop-ins:
    - name: 15-deps.conf
      content: |
        [Unit]
        Description=Etcd2 - unit for etcd
        Wants=smilodon.service
        [Service]
        PermissionsStartOnly=true
        RuntimeDirectory=etcd2
        RuntimeDirectoryMode=0700
        EnvironmentFile=/etc/etcd-environment
        EnvironmentFile=/run/smilodon/environment
        ExecStartPre=/usr/bin/chown -R etcd:etcd /etc/ssl/kubernetes /var/lib/etcd2
        ExecStartPre=/usr/bin/systemctl --quiet is-active kmsctl-certs.service
        ExecStart=
        ExecStart=-/usr/bin/etcd2 --name=node$${NODE_ID} \
        --initial-advertise-peer-urls https://$${NODE_IP}:2380 \
        --advertise-client-urls https://$${NODE_IP}:2379
        Restart=on-failure
        RestartSec=10
  - name: smilodon.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Smilodon - manage ebs+eni attachment
      [Service]
      Environment="URL=${smilodon_release_url}"
      Environment="OUTPUT_FILE=/opt/bin/smilodon"
      Environment="MD5SUM=${smilodon_release_md5}"
      EnvironmentFile=/etc/aws-environment
      ExecStartPre=/usr/bin/systemctl --quiet is-active kmsctl-certs.service
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/bash -c 'until [[ -x $${OUTPUT_FILE} ]] && [[ $(md5sum $${OUTPUT_FILE} | cut -f1 -d" ") == $${MD5SUM} ]]; do wget -q -O $${OUTPUT_FILE} $${URL} && chmod +x $${OUTPUT_FILE}; done'
      ExecStart=/opt/bin/smilodon --filters=tag:Env=${environment}
      Restart=on-failure
      RestartSec=10
  - name: kmsctl-certs.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=KMSCtl - download certs
      [Service]
      Type=notify
      NotifyAccess=all
      RemainAfterExit=yes
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/mkdir -p /var/lib/etcd2
      ExecStartPre=/usr/bin/mkdir -p /etc/ssl/kubernetes
      ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
      ExecStartPre=/usr/bin/chown -R etcd:etcd /var/lib/etcd2
      ExecStartPre=/usr/bin/chown -R root:root /etc/kubernetes/manifests /etc/ssl/kubernetes
      ExecStartPre=/usr/bin/chmod 0744 /etc/ssl/kubernetes /var/lib/etcd2
      ExecStartPre=/usr/bin/wget https://github.com/gambol99/kmsctl/releases/download/v1.0.4/kmsctl-linux-amd64 -O /opt/bin/kmsctl
      ExecStartPre=/usr/bin/chmod +x /opt/bin/kmsctl
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdcertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdkeyobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${mastercertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${masterkeyobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdproxycertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdproxykeyobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${cacertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/kubernetes/manifests/ Manifests/kube-apiserver.yml
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/kubernetes/manifests/ Manifests/kube-controller-manager.yml
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/kubernetes/manifests/ Manifests/kube-proxy.yml
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/kubernetes/manifests/ Manifests/kube-scheduler.yml
      ExecStartPre=/usr/bin/bash -c "chmod 0644 /etc/ssl/kubernetes/* /etc/kubernetes/manifests/*"
      ExecStartPre=/usr/bin/bash -c "cp -f /etc/ssl/kubernetes/* /etc/ssl/certs"
      ExecStartPre=/usr/sbin/update-ca-certificates
      ExecStart=/usr/bin/systemd-notify --ready --status="successfully downloaded the certs"
      Restart=on-failure
      RestartSec=10
      TimeoutStartSec=300
# Workaround until this has been fixed: https://github.com/systemd/systemd/issues/1784
  - name: networkd-restart.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=Restart systemd-networkd when DOWN interface is found
      [Service]
      ExecStart=/usr/bin/bash -c 'while true; do ip -o -4 link show | grep -q "eth[0-1]:.*state DOWN" && systemctl restart systemd-networkd; sleep 60; done'
      Restart=always
      RestartSec=10
  - name: 20-eth1.network
    runtime: false
    content: |
      [Match]
      Name=eth1
      [Network]
      DHCP=ipv4
      [DHCP]
      UseDNS=false
      SendHostname=true
      UseRoutes=false
      RouteMetric=2048
  - name: docker.service
    drop-ins:
    - name: 10-opts.conf
      content: |
        [Unit]
        Requires=flanneld.service
        After=flanneld.service
        [Service]
        EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env
        Environment="DOCKER_OPTS=--iptables=false --log-opt max-size=100m --log-opt max-file=1 --default-ulimit=nofile=32768:32768 --default-ulimit=nproc=16384:16384"
  - name: xvde-mkfs.service
    content: |
      [Unit]
      Description=Format /dev/xvde
      After=dev-xvde.device
      Requires=dev-xvde.device
      [Service]
      Type=oneshot
      ExecStart=/usr/bin/bash -c '/usr/bin/lsblk -n -o FSTYPE /dev/xvde | grep ext4 || (/usr/sbin/wipefs -f /dev/xvde && /usr/sbin/mkfs.ext4 /dev/xvde)'
  - name: var-lib-etcd2.mount
    content: |
      [Unit]
      Description=Mount etcd2 data volume
      Before=etcd2.service
      After=xvde-mkfs.service
      Requires=xvde-mkfs.service
      [Mount]
      What=/dev/xvde
      Where=/var/lib/etcd2
      Type=ext4
  - name: var-lib-etcd2.automount
    command: start
    enable: true
    content: |
      [Unit]
      Description=Auto mount etcd2 data volume
      [Automount]
      Where=/var/lib/etcd2
  - name: flanneld.service
    command: start
    enable: true
    drop-ins:
    - name: 50-network-config.conf
      content: |
        [Service]
        RestartSec=30
        Restart=on-failure
        Environment="ETCD_SSL_DIR=/etc/ssl/kubernetes"
        EnvironmentFile=/etc/etcd-environment
        EnvironmentFile=/run/flannel/options.env
        ExecStartPre=/usr/bin/systemctl --quiet is-active etcd2.service
        ExecStartPre=/usr/bin/systemctl --quiet is-active kmsctl-certs.service
        ExecStartPre=/usr/bin/etcdctl --peers $${FLANNELD_ETCD_ENDPOINTS} set /coreos.com/network/config '{"Network":"${flannel_cidr}","Backend":{"Type":"vxlan"}}'

  - name: kubelet.service
    command: start
    content: |
      [Service]
      Environment=KUBELET_VERSION=v1.5.2_coreos.0
      Environment="RKT_OPTS=--uuid-file-save=/var/run/kubelet-pod.uuid \
        --volume var-log,kind=host,source=/var/log \
        --mount volume=var-log,target=/var/log \
        --volume dns,kind=host,source=/etc/resolv.conf \
        --mount volume=dns,target=/etc/resolv.conf" \
        --volume ssl,kind=host,source=/etc/ssl/kubernetes \
        --mount volume=ssl,target=/etc/kubernetes/ssl"
      ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
      ExecStartPre=/usr/bin/mkdir -p /var/log/containers
      ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/run/kubelet-pod.uuid
      ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --api-servers=http://127.0.0.1:8080 \
        --register-schedulable=false \
        --cni-conf-dir=/etc/kubernetes/cni/net.d \
        --container-runtime=docker \
        --allow-privileged=true \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --cluster_dns=10.3.0.10 \
        --cluster_domain=cluster.local
      ExecStop=-/usr/bin/rkt stop --uuid-file=/var/run/kubelet-pod.uuid
      Restart=on-failure
      RestartSec=10
      [Install]
      WantedBy=multi-user.target

write_files:
- path: /opt/bin/host-rkt
  permissions: 0755
  owner: root:root
  content: |
    #!/bin/sh
    exec nsenter -m -u -i -n -p -t 1 -- /usr/bin/rkt "$@"
- path: /etc/kubernetes/cni/docker_opts_cni.env
  permissions: 0444
  owner: root
  content: |
    DOCKER_OPT_BIP=""
    DOCKER_OPT_IPMASQ=""
- path: /etc/kubernetes/cni/net.d/10-flannel.conf
  permissions: 0444
  owner: root
  content: |
    {
    "name": "podnet",
    "type": "flannel",
    "delegate": {
        "isDefaultGateway": true
      }
    }
- path: /etc/kubernetes/cloud.cfg
  permissions: 0444
  owner: root
  content: |
    [Global]
    KubernetesClusterTag = "${environment}"
    DisableSecurityGroupIngress = true
- path: /etc/sysctl.d/10-disable-ipv6.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv6.conf.all.disable_ipv6 = 1
- path: /etc/sysctl.d/baselayout.conf
  permissions: 0644
  owner: root
  content: |
    net.ipv4.ip_forward = 1
    net.ipv4.conf.default.rp_filter = 2
    net.ipv4.conf.all.rp_filter = 2
    kernel.kptr_restrict = 1
- path: /etc/aws-environment
  permissions: 0444
  content: |
    AWS_REGION=${region}
    DNS_ZONE_NAME=${zonename}
    ENVIRONMENT=${environment}
- path: /etc/profile.env
  content: |
    export ETCDCTL_ENDPOINT=https://127.0.0.1:2379
    export ETCDCTL_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    export ETCDCTL_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    export ETCDCTL_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
    source /run/smilodon/environment
    source /etc/etcd-environment
- path: /etc/etcd-environment
  permissions: 0644
  content: |
    ETCD_TRUSTED_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    ETCD_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    ETCD_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
    ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    ETCD_PEER_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    ETCD_PEER_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
    ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
    ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
    ETCD_CLIENT_CERT_AUTH=true
    ETCD_PEER_CLIENT_CERT_AUTH=true
    ETCD_DATA_DIR=/var/lib/etcd2
    ETCD_INITIAL_CLUSTER_STATE=new
    ETCD_INITIAL_CLUSTER_TOKEN=etcd-terrakube
    ETCD_INITIAL_CLUSTER=${etcd_memberlist}
    ETCDCTL_ENDPOINT=https://127.0.0.1:2379
    ETCDCTL_CA_FILE=/etc/ssl/kubernetes/${cacertobject}
    ETCDCTL_CERT_FILE=/etc/ssl/kubernetes/${etcdcertobject}
    ETCDCTL_KEY_FILE=/etc/ssl/kubernetes/${etcdkeyobject}
